/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva_bol.h"

int m[10][4],
    used_seats = 0,
    MAX_SEATS = 10*4,
    R = 10,
    C = 4;

int * ask_for_seat_1_svc(int r, int c, struct svc_req *rqstp) {
    static int result;

    if (r < 1 || r > R || c < 1 || c > C) {
        result = 3;
        return &result;
    }
    
    if (used_seats == MAX_SEATS)
    	result = 0;
    else {
        if (m[r-1][c-1] != 0)
        	result = 1;
        else {
            m[r-1][c-1] = 1;      // 1-index => 0-index
            used_seats++;
            result = 2;
        }
    }

    return &result;
}
