/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva_bol.h"


void reserva_bol_1(char *host, int r, int c){
	CLIENT *clnt;
	int R, C, i, j;
	char * *answer;

#ifndef	DEBUG
	clnt = clnt_create (host, RESERVA_BOL, RESERVAL_BOL_VERS_2, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while (1) {
		int try = 3;
		while (try--) {
			answer = ask_for_seat_1(r,c,clnt); 
			if (answer == (char **) NULL)
				printf("ERROR: no se pudo conectar. Reintentando.\n");
			else break;
		}

		if (try == -1) { 
			printf("ERROR: tiempo de espera agotado.\n");
			exit(0);
		}
		//printf("ans: %s\n", *answer);

		switch (*answer[0]) {
	    	case '0':
	    		printf("Vagon lleno.\n");
	    		exit(0);
	    	case '1':
	    		printf("Puesto ocupado. Puestos disponibles:\n ");
	    		R = (*answer)[1]-48;
	    		C = (*answer)[2]-48;
	    		if (R == 0) R = 10;
	            for (i=0; i<R; i++) {
	                for (j=0; j<C; j++) {
	                    if ((*answer+3)[i*C+j] != '1') printf("(%d,%d) | ", i+1,j+1);
	                }
	            }
	    		printf("\nIngrese numero de fila y columna (<fila> <columna>): ");
	    		scanf("%d %d", &r, &c);
	    		break;
	    	case '2':
	    		printf("Puesto reservado con exito.\n");
	    		exit(0);
	    	case '3':
	    		printf("Rango errado.\n");
	    		exit(0);
	    	default:
	    		printf("El servidor esta presentando una falla. Recibido: %s.\n", *answer);
	    		exit(0);
		}
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void parse_arguments(int argc, char *argv[], int *r, int *c) {
	char * bad_syntax_msg = "Sintaxis errada de argumentos del programa. Sintaxis correcta: reserva_bol_cli <ip-servidor> -p <puerto> -f <fila> -c <columna>\n";

	if (argc != 8) {
		printf(bad_syntax_msg);
		exit(1);
	}

    if (strcmp(argv[2], "-p")) {
    	printf(bad_syntax_msg);
    	exit(1);
    }
    
    if (!strcmp(argv[4], "-f"))
        *r = atoi(argv[5]);
    else {
    	printf(bad_syntax_msg);
    	exit(1);
    }

    if (!strcmp(argv[6], "-c"))
        *c = atoi(argv[7]);
    else {
    	printf(bad_syntax_msg);
    	exit(1);
    }
}



int main (int argc, char *argv[]) {
	char *host;
	int r, c;

	parse_arguments(argc, argv, &r, &c);
	host = argv[1];
	reserva_bol_1 (host,r,c);
	exit (0);
}
