/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESERVA_BOL_H_RPCGEN
#define _RESERVA_BOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ask_for_seat_1_argument {
	int arg1;
	int arg2;
};
typedef struct ask_for_seat_1_argument ask_for_seat_1_argument;

#define RESERVA_BOL 0x31111111
#define RESERVAL_BOL_VERS_2 1

#if defined(__STDC__) || defined(__cplusplus)
#define ask_for_seat 1
extern  char ** ask_for_seat_1(int , int , CLIENT *);
extern  char ** ask_for_seat_1_svc(int , int , struct svc_req *);
extern int reserva_bol_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ask_for_seat 1
extern  char ** ask_for_seat_1();
extern  char ** ask_for_seat_1_svc();
extern int reserva_bol_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ask_for_seat_1_argument (XDR *, ask_for_seat_1_argument*);

#else /* K&R C */
extern bool_t xdr_ask_for_seat_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RESERVA_BOL_H_RPCGEN */
