/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "reserva_bol.h"

bool_t
xdr_ask_for_seat_1_argument (XDR *xdrs, ask_for_seat_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
